### ISSUE TITLE
libMantidGeometry.so: undefined symbol: _ZNK2mu11ParserError6GetMsgEv

### ISSUE THREAD

**Issue by beenje** [mantidproject/conda-recipes#27]
I have installed and run successfully mantid in a centos:7 docker container in the past.
When trying to build a newer version, I get the following error:
```
(mantid) [root@ace3ff8234ea /]# python
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 03:09:43)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mantid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/mantid/lib/python3.6/site-packages/mantid/__init__.py", line 74, in <module>
    import mantid.geometry as geometry
  File "/opt/conda/envs/mantid/lib/python3.6/site-packages/mantid/geometry/__init__.py", line 14, in <module>
    from ._geometry import *
ImportError: /opt/conda/envs/mantid/lib/python3.6/site-packages/mantid/geometry/../../../../libMantidGeometry.so: undefined symbol: _ZNK2mu11ParserError6GetMsgEv
```

This is the version installed:
```
# conda list | grep mantid
# packages in environment at /opt/conda/envs/mantid:
mantid-framework          3.13.0           py36ha18e881_0    mantid
nexus                     4.4.3                         0    mantid
poco                      1.7.3                         0    mantid
```

Here is a Dockerfile to reproduce the issue:
```
FROM centos:7

ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANGUAGE=en_US.UTF-8

COPY conda.repo /etc/yum.repos.d/

RUN rpm --import https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc \
    && yum update -y \
    && yum install -y \
      conda \
      mesa-libGLU-devel \
    && yum clean all \
    && rm -rf /var/cache/yum

ENV PATH /opt/conda/bin:$PATH

RUN conda create --quiet --yes \
    -c mantid \
    -c conda-forge \
    -n mantid \
      python=3.6 \
      'mantid-framework' \
    && conda clean -tipsy

ENV PATH /opt/conda/envs/mantid/bin:$PATH
```

Any idea what the problem is?

**Comment by beenje** [comment]
OK, I just managed to pinpoint the issue to muparser.
Downgrading from 2.2.5-hf484d3e_2005 to 2.2.5-hfc679d8_1005 solved the issue:
`muparser: 2.2.5-hf484d3e_2005 conda-forge --> 2.2.5-hfc679d8_1005 conda-forge`

Looks like this newer release was rebuilt with a new compiler: https://github.com/conda-forge/muparser-feedstock/commit/d7bec2d332750a8d6350aeba3005539777a4b315

Did you pin muparser to a specific version/build?

**Comment by yxqd** [comment]
Yes we have seen this before. The recipe currently uses a specific version of muparser: https://github.com/mantidproject/conda-recipes/blob/6a9b274f23cd468527302cd6bd83dde280b8788d/framework/meta.yaml#L22
