### ISSUE TITLE
Python 3.6 workbench conda package errors on QVariant issue

### ISSUE THREAD

**Issue by marshallmcdonnell** [mantidproject/conda-recipes#33]
Testing the workbench conda packages [here](https://anaconda.org/mantid/mantid-workbench), I got the following error regarding QVariant:

```
QVariant::load: unable to load type 67.
Traceback (most recent call last):
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/bin/workbench-script", line 11, in <module>
    load_entry_point('MantidWorkbench==3.13.20190306.1716', 'gui_scripts', 'workbench')()
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/workbench/app/mainwindow.py", line 23, in <module>
    from workbench.widgets.settings.presenter import SettingsPresenter
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/workbench/widgets/settings/presenter.py", line 13, in <module>
    from workbench.widgets.settings.general.presenter import GeneralSettings
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/workbench/widgets/settings/general/presenter.py", line 13, in <module>
    from workbench.config import CONF
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/workbench/config/__init__.py", line 53, in <module>
    CONF = UserConfig(ORGANIZATION, APPNAME, defaults=DEFAULTS)
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/workbench/config/user.py", line 52, in __init__
    value = self.get(key)
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py36/lib/workbench/config/user.py", line 82, in get
    value = self.qsettings.value(option)
TypeError: unable to convert a C++ 'QColor' instance to a Python object
Gtk-Message: 17:42:52.778: Failed to load module "atk-bridge"
Gtk-Message: 17:42:52.783: Failed to load module "canberra-gtk-module"
error-[Notice] No information shared
error-[Error] Continue working.
```

The last 3 lines maybe the culprit. Possibly need to add them to the recipe (either as a conda package or system library like we do for OpenGL)

**To reproduce**
```
conda create -n test-env -q python=3.6
conda activate test-env
conda install conda -y
conda install -c mantid mantid-workbench
PYTHONPATH=""
mantidworkbench
```

**Comment by yxqd** [comment]
@marshallmcdonnell this seems solved?

**Comment by marshallmcdonnell** [comment]
Yes, PR #35 closed this, sorry.
