### ISSUE TITLE
Python 2.7 workbench conda package errors 

### ISSUE THREAD

**Issue by marshallmcdonnell** [mantidproject/conda-recipes#34]
Error on the `psutil` import error (may need to be added to package) and possibly a `xcb` error based on the message `This application failed to start because it could not find or load the Qt platform plugin "xcb"`

```
Traceback (most recent call last):
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py27/bin/workbench-script", line 11, in <module>
    load_entry_point('MantidWorkbench==3.13.20190308.1707', 'gui_scripts', 'workbench')()
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py27/lib/workbench/app/mainwindow.py", line 60, in <module>
    from workbench.projectrecovery.projectrecovery import ProjectRecovery  # noqa
  File "/home/ntm/miniconda/envs/mantid-workbench-download-py27/lib/workbench/projectrecovery/projectrecovery.py", line 18, in <module>
    import psutil
ImportError: No module named psutil
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
```

**To reproduce**
```
conda create -n test-env -q python=2.7
conda activate test-env
conda install conda -y
conda install -c mantid mantid-workbench
PYTHONPATH=""
mantidworkbench
```

**Comment by marshallmcdonnell** [comment]
Related? https://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

**Comment by yxqd** [comment]
I tried it too. For me
* psutil and requests is missing
* it looks like version of `icu` needs to be pinned

**Comment by marshallmcdonnell** [comment]
Right now I have icu=54.1 (not pinned). I think this is actually set by one of the Qt libraries since it does a max pin. 

There is icu=58.2 available [from their conda-forge channel](https://anaconda.org/conda-forge/icu).

Thoughts on what icu version needs to be pinned?

**Comment by yxqd** [comment]
@marshallmcdonnell is this solved?

**Comment by marshallmcdonnell** [comment]
Sorry, yes, this is fixed. I think PR #35  should have closed this.

**Comment by yxqd** [comment]
Thanks! @marshallmcdonnell
