### ISSUE TITLE
Anaconda mantid-workbench fails to run workbench - 2 mantid installs in package

### ISSUE THREAD

**Issue by marshallmcdonnell** [mantidproject/conda-recipes#36]
Our [ADDIE](https://github.com/neutrons/addie) CI keeps picking up broken nightly anaconda packages (label: `nightly`) for `mantid-workbench`. The last working version of Mantid Workbench was 4.0.20190416.

Offline talks with @yxqd seem to show that there are two versions of mantid in these packages that are only triggered from the `mantidworkbench` command:
> Running from a simple python command line, `from mantid import kernel` works, and it is importing from `$PREFIX/lib/pythonX.Y/site-packages/mantid`, as expected. But when using the `mantidworkbench` script, it is using mantid  code in a different directory: `$PREFIX/lib/mantid`

> Yes I examined the conda tarballs for mantid-workbench, and the difference is there: the new tarball has mantid python source under $PREFIX/lib/mantid while earlier tarballs do not have that.

For the error output, we have:

**Command:**
```
 xvfb-run --server-args="-screen 0 640x480x24" --auto-servernum mantidworkbench --help
```
**Output:**
```

Traceback (most recent call last):
  File "/home/travis/miniconda/envs/addie_env/bin/workbench-script", line 11, in <module>
    load_entry_point('MantidWorkbench==4.0.20190604.1250', 'gui_scripts', 'workbench')()
  File "/home/travis/miniconda/envs/addie_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/travis/miniconda/envs/addie_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/travis/miniconda/envs/addie_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/travis/miniconda/envs/addie_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/miniconda/envs/addie_env/lib/python2.7/site-packages/workbench/app/mainwindow.py", line 22, in <module>
    from mantid.api import FrameworkManagerImpl
  File "/home/travis/miniconda/envs/addie_env/lib/mantid/__init__.py", line 106, in <module>
    from mantid import kernel as _kernel
  File "/home/travis/miniconda/envs/addie_env/lib/mantid/kernel/__init__.py", line 38, in <module>
    import_mantid_cext('._kernel', 'mantid.kernel', globals())
  File "/home/travis/miniconda/envs/addie_env/lib/mantid/utils.py", line 37, in import_mantid_cext
    raise ImportError(msg)
ImportError: First import of "._kernel" failed with "No module named _kernel". Second import of "_kernel" failed with "No module named _kernel"
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/addie_env/scripts/ErrorReporter/error_dialog_app.py", line 23, in <module>
    import mantid  # noqa
  File "/home/travis/miniconda/envs/addie_env/lib/mantid/__init__.py", line 106, in <module>
    from mantid import kernel as _kernel
  File "/home/travis/miniconda/envs/addie_env/lib/mantid/kernel/__init__.py", line 38, in <module>
    import_mantid_cext('._kernel', 'mantid.kernel', globals())
  File "/home/travis/miniconda/envs/addie_env/lib/mantid/utils.py", line 37, in import_mantid_cext
    raise ImportError(msg)
ImportError: First import of "._kernel" failed with "No module named _kernel". Second import of "_kernel" failed with "No module named _kernel"
```

Just consolidating this info into an issue. Sorry, I haven't had the chance to dig into this.

**Comment by marshallmcdonnell** [comment]
This has been fixed in the Sep. 3rd, 2019 package.

Before that, the working package was April 16th, 2019.

I removed all the packages with `broken` between these two dates:

![image](https://user-images.githubusercontent.com/17032543/65914816-19e19f00-e3a0-11e9-8157-e3bd3f097e79.png)
