### ISSUE TITLE
jenkins build problem 07082019

### ISSUE THREAD

**Issue by yxqd** [mantidproject/conda-recipes#37]
* The problem was with github DNS load balancing and firewall. Switching to use https makes https://builds.mantidproject.org/view/Master%20Pipeline/job/master_condarecipes_update/ and https://builds.mantidproject.org/view/Master%20Pipeline/job/master_systemtests-conda/ work
* The current problem is with https://builds.mantidproject.org/view/Master%20Pipeline/job/master_create_conda_linux_pkgs/. when using miniconda3 docker image, installation of conda-build fails with `undefined symbol: archive_errno`, similar to https://github.com/ContinuumIO/docker-images/issues/95

**Comment by yxqd** [comment]
* Running https://github.com/mantidproject/conda-recipes/blob/ac8a6bb03a7c4494a2ef3f7194808fe52456110f/docker/run_docker_build_continuumio-mc2.sh from a ubuntu 16.04 box finished without problem. So is the problem just with mano?

**Comment by yxqd** [comment]
* Building outside of jenkins at manos works. Why it does not work as jenkins build?

**Comment by yxqd** [comment]
Switched to use baldrick. Mostly working. The one fails now is https://builds.mantidproject.org/view/Master%20Pipeline/job/master_create_conda_linux_pkgs/

Error message:
```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1324, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 735, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 2038, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 509, in finalize_metadata
    exclude_pattern)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 371, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 362, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 350, in get_upstream_pins
    specs = _read_specs_from_package(loc, dist)
  File "/opt/conda/lib/python3.7/site-packages/conda/exports.py", line 198, in __call__
    value = self.func(*args, **kw)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 245, in _read_specs_from_package
    if not specs and os.path.isfile(pkg_loc):
  File "/opt/conda/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by yxqd** [comment]
Going to try to not forcing conda-build 3.17 again in https://github.com/mantidproject/conda-recipes/commits/master/docker/run_docker_build_continuumio-mc2.sh

**Comment by yxqd** [comment]
All works now
